name: Firmware

on:
  workflow_dispatch:
  workflow_call:
  push:
    paths:
      - Makefile
      - ReflexMPG/**

jobs:
  build:
    name: Build Firmware Combinations
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Arduino CLI
        uses: arduino/setup-arduino-cli@v1
      - name: Install Arduino base platform
        run: arduino-cli core install arduino:avr
      - name: Install Arduino LUFA platform
        run: arduino-cli core install Arduino-LUFA:avr --additional-urls https://github.com/Palatis/Arduino-Lufa/raw/master/package_arduino-lufa_index.json
      - name: Build All
        run: make all
      - uses: actions/upload-artifact@v3
        with:
          name: firmware
          path: firmware/
